"""Starter parts library. Specs are typical values; always confirm with the datasheet.

'marks' are common top markings (mostly SMD) that map to the part. SMD markings are
manufacturer dependent, so treat them as strong hints rather than guarantees.
"""

SEED_PARTS = [
    # ------------------------------------------------------------ BJT transistors
    dict(pn="2N2222A", cat="Transistor (BJT)", desc="NPN general purpose switching transistor",
         pkg="TO-18 / TO-92 (PN2222A) / SOT-23 (MMBT2222A)",
         specs="NPN, Vceo 40 V, Ic 600-800 mA, hFE 100-300, fT ~300 MHz",
         marks=["1P", "MMBT2222A"], notes="SMD MMBT2222A is marked 1P. Good for driving relays/LEDs up to ~500 mA."),
    dict(pn="2N3904", cat="Transistor (BJT)", desc="NPN small-signal transistor",
         pkg="TO-92 / SOT-23 (MMBT3904)", specs="NPN, Vceo 40 V, Ic 200 mA, hFE 100-300",
         marks=["1AM", "MMBT3904"], notes="Pinout in TO-92 is EBC (flat face towards you). SMD MMBT3904 marked 1AM."),
    dict(pn="2N3906", cat="Transistor (BJT)", desc="PNP small-signal transistor (complement of 2N3904)",
         pkg="TO-92 / SOT-23 (MMBT3906)", specs="PNP, Vceo -40 V, Ic -200 mA, hFE 100-300",
         marks=["2A", "MMBT3906"], notes="SMD MMBT3906 marked 2A."),
    dict(pn="BC547", cat="Transistor (BJT)", desc="NPN general purpose transistor",
         pkg="TO-92", specs="NPN, Vceo 45 V, Ic 100 mA, hFE 110-800 depending on suffix (A/B/C)",
         notes="Pinout CBE (flat face towards you). BC557 is the PNP complement."),
    dict(pn="BC557", cat="Transistor (BJT)", desc="PNP general purpose transistor (complement of BC547)",
         pkg="TO-92", specs="PNP, Vceo -45 V, Ic -100 mA"),
    dict(pn="BC337", cat="Transistor (BJT)", desc="NPN medium-current transistor",
         pkg="TO-92", specs="NPN, Vceo 45 V, Ic 800 mA, hFE 100-630", notes="BC327 is the PNP complement."),
    dict(pn="BC847", cat="Transistor (BJT)", desc="NPN small-signal SMD transistor",
         pkg="SOT-23", specs="NPN, Vceo 45 V, Ic 100 mA", marks=["1F", "1E", "1G"],
         notes="Marking 1E/1F/1G = BC847A/B/C gain grades."),
    dict(pn="BC857", cat="Transistor (BJT)", desc="PNP small-signal SMD transistor",
         pkg="SOT-23", specs="PNP, Vceo -45 V, Ic -100 mA", marks=["3F", "3E", "3G"]),
    dict(pn="S8050", cat="Transistor (BJT)", desc="NPN transistor, very common on Chinese modules",
         pkg="TO-92 / SOT-23", specs="NPN, Vceo 25 V, Ic 500 mA (1.5 A peak)", marks=["J3Y"],
         notes="SMD version marked J3Y (a bare J3 may be an S9013 instead). Complement is S8550 (2TY)."),
    dict(pn="S8550", cat="Transistor (BJT)", desc="PNP transistor, complement of S8050",
         pkg="TO-92 / SOT-23", specs="PNP, Vceo -25 V, Ic -500 mA", marks=["2TY"]),
    dict(pn="TIP120", cat="Transistor (BJT)", desc="NPN Darlington power transistor",
         pkg="TO-220", specs="NPN Darlington, Vceo 60 V, Ic 5 A (8 A peak), hFE >1000, Vce(sat) ~2 V",
         notes="Drops ~2 V, so gets hot. A logic-level MOSFET is usually a better switch."),
    # ------------------------------------------------------------------- MOSFETs
    dict(pn="IRLZ44N", cat="MOSFET", desc="N-channel logic-level power MOSFET",
         pkg="TO-220", specs="55 V, 47 A, Rds(on) ~25 mOhm at Vgs=5 V, Vgs(th) 1-2 V",
         notes="Fine from 5 V; marginal from 3.3 V logic at high current."),
    dict(pn="IRFZ44N", cat="MOSFET", desc="N-channel power MOSFET (NOT logic level)",
         pkg="TO-220", specs="55 V, 49 A, Rds(on) ~17.5 mOhm at Vgs=10 V, Vgs(th) 2-4 V",
         notes="Needs ~10 V gate drive for low Rds(on). Don't drive hard from a 3.3 V GPIO."),
    dict(pn="IRF520", cat="MOSFET", desc="N-channel power MOSFET (NOT logic level)",
         pkg="TO-220", specs="100 V, 9.2 A, Rds(on) 0.27 Ohm at Vgs=10 V",
         notes="The common 'IRF520 module' is poor from 3.3/5 V: high Rds(on), gets hot."),
    dict(pn="AO3400", cat="MOSFET", desc="N-channel logic-level MOSFET, SMD",
         pkg="SOT-23", specs="30 V, 5.7 A, Rds(on) ~30 mOhm at Vgs=4.5 V", marks=["A09T"],
         notes="Works well from 3.3 V gate drive."),
    dict(pn="AO3401", cat="MOSFET", desc="P-channel MOSFET, SMD (reverse-polarity / high-side switch)",
         pkg="SOT-23", specs="-30 V, -4 A, Rds(on) ~60 mOhm at Vgs=-4.5 V", marks=["A19T"]),
    dict(pn="2N7000", cat="MOSFET", desc="N-channel small-signal MOSFET",
         pkg="TO-92", specs="60 V, 200 mA, Rds(on) ~5 Ohm", notes="Handy for level shifting and light loads."),
    dict(pn="BS170", cat="MOSFET", desc="N-channel small-signal MOSFET",
         pkg="TO-92", specs="60 V, 500 mA, Rds(on) ~5 Ohm"),
    # -------------------------------------------------------------------- diodes
    dict(pn="1N4148", cat="Diode", desc="Fast small-signal switching diode",
         pkg="DO-35 / SOD-123 (1N4148W)", specs="100 V, 200-300 mA, trr 4 ns, Vf ~0.7 V", marks=["T4", "1N4148W"],
         notes="SMD 1N4148W marked T4."),
    dict(pn="1N4007", cat="Diode", desc="General purpose rectifier diode",
         pkg="DO-41 / SMA (M7)", specs="1000 V, 1 A, Vf ~1 V", marks=["M7"],
         notes="Slow recovery: use as flyback across relay coils, not for fast switching."),
    dict(pn="1N5408", cat="Diode", desc="3 A rectifier diode", pkg="DO-201", specs="1000 V, 3 A"),
    dict(pn="1N5819", cat="Diode", desc="Schottky rectifier", pkg="DO-41",
         specs="40 V, 1 A, Vf ~0.45 V at 1 A", notes="SMD equivalent is SS14."),
    dict(pn="SS14", cat="Diode", desc="Schottky rectifier, SMD", pkg="SMA",
         specs="40 V, 1 A, Vf ~0.5 V", marks=["SS14"], notes="SMD equivalent of 1N5819. SS34 is the 3 A version."),
    dict(pn="SS34", cat="Diode", desc="Schottky rectifier, SMD 3 A", pkg="SMA/SMB", specs="40 V, 3 A", marks=["SS34"]),
    dict(pn="1N5822", cat="Diode", desc="Schottky rectifier 3 A", pkg="DO-201", specs="40 V, 3 A, Vf ~0.5 V"),
    dict(pn="1N4733A", cat="Diode", desc="5.1 V zener diode, 1 W", pkg="DO-41", specs="Vz 5.1 V, 1 W",
         notes="1N4728A = 3.3 V, 1N4742A = 12 V (same 1 W series)."),
    dict(pn="1N4728A", cat="Diode", desc="3.3 V zener diode, 1 W", pkg="DO-41", specs="Vz 3.3 V, 1 W"),
    dict(pn="DB107", cat="Diode", desc="Bridge rectifier, 1 A", pkg="DIP-4", specs="1000 V, 1 A"),
    # ---------------------------------------------------------------- regulators
    dict(pn="LM7805", cat="Regulator", desc="5 V linear regulator (L7805)", pkg="TO-220",
         specs="5 V, 1 A, dropout ~2 V, Vin max 35 V, Iq ~6 mA",
         notes="Wastes (Vin-5)*I as heat. Needs a heatsink above ~300 mA at 12 V in."),
    dict(pn="LM7812", cat="Regulator", desc="12 V linear regulator", pkg="TO-220", specs="12 V, 1 A, dropout ~2 V, Vin max 35 V"),
    dict(pn="AMS1117-3.3", cat="Regulator", desc="3.3 V LDO regulator", pkg="SOT-223",
         specs="3.3 V, 800 mA, dropout ~1.1 V, Vin max 15 V, min load ~5-10 mA",
         marks=["1117-3.3", "1117-33", "1117"],
         notes="On most ESP32/ESP8266 dev boards. Needs >=4.4 V in. Gets hot above ~300 mA from 5 V."),
    dict(pn="AP2112K-3.3", cat="Regulator", desc="3.3 V low-dropout regulator", pkg="SOT-23-5",
         specs="3.3 V, 600 mA, dropout ~250 mV, Iq ~55 uA", notes="Used on many newer ESP32 boards."),
    dict(pn="HT7333", cat="Regulator", desc="3.3 V low-quiescent LDO", pkg="SOT-89 / TO-92",
         specs="3.3 V, 250 mA, Iq ~4 uA, dropout ~170 mV", marks=["7333"]),
    dict(pn="MCP1700-3302", cat="Regulator", desc="3.3 V ultra-low-Iq LDO", pkg="SOT-23 / TO-92",
         specs="3.3 V, 250 mA, Iq 1.6 uA, dropout ~178 mV", notes="Great for battery/deep-sleep projects."),
    dict(pn="LM317", cat="Regulator", desc="Adjustable linear regulator", pkg="TO-220",
         specs="1.25-37 V, 1.5 A, dropout ~2 V", notes="Vout = 1.25 * (1 + R2/R1)."),
    dict(pn="LM2596", cat="Regulator", desc="Buck (step-down) converter", pkg="TO-263 / module",
         specs="4.5-40 V in, 3 A, 150 kHz, ~85% efficient", notes="Common cheap buck modules. Set Vout with the trimmer BEFORE connecting a load."),
    dict(pn="MP1584", cat="Regulator", desc="Mini buck converter", pkg="module",
         specs="4.5-28 V in, 3 A max (about 1.5-2 A practical), ~90% efficient"),
    dict(pn="MT3608", cat="Regulator", desc="Boost (step-up) converter", pkg="SOT-23-6 / module",
         specs="2-24 V in, up to 28 V out, ~1 A practical", notes="Input current climbs fast when the battery sags."),
    dict(pn="TP4056", cat="Regulator", desc="1 A Li-ion/LiPo linear charger", pkg="SOP-8 / module",
         specs="4.2 V, up to 1 A. Rprog 1.2k=1 A, 2k=580 mA, 10k=130 mA", marks=["TP4056"],
         notes="Plain TP4056 modules have NO battery protection; get the DW01+8205 version."),
    # ----------------------------------------------------------------------- ICs
    dict(pn="NE555", cat="IC", desc="Timer", pkg="DIP-8 / SOIC-8", specs="4.5-16 V, 200 mA output (LMC555/TLC555 work at 3.3 V)"),
    dict(pn="LM358", cat="IC", desc="Dual op-amp", pkg="DIP-8 / SOIC-8", specs="3-32 V, output swings to ~Vcc-1.5 V, not rail-to-rail"),
    dict(pn="LM393", cat="IC", desc="Dual comparator", pkg="DIP-8 / SOIC-8", specs="2-36 V, open-collector outputs (need pull-ups)"),
    dict(pn="74HC595", cat="IC", desc="8-bit shift register with output latch", pkg="DIP-16",
         specs="2-6 V, 6 mA per output", notes="Expand outputs with 3 GPIO pins."),
    dict(pn="ULN2003A", cat="IC", desc="7-channel Darlington driver", pkg="DIP-16",
         specs="500 mA per channel, 50 V, built-in flyback diodes", notes="Used on 28BYJ-48 stepper boards. Has ~1 V drop."),
    dict(pn="L293D", cat="IC", desc="Dual H-bridge motor driver", pkg="DIP-16", specs="4.5-36 V, 600 mA per channel (1.2 A peak)"),
    dict(pn="L298N", cat="IC", desc="Dual H-bridge motor driver", pkg="Multiwatt-15 / module",
         specs="Up to 46 V, 2 A per channel, ~2 V drop", notes="Bipolar: wasteful and hot. Modern MOSFET drivers are better."),
    dict(pn="PC817", cat="IC", desc="Optocoupler", pkg="DIP-4 / SOP-4", specs="CTR 50-600%, LED Vf ~1.2 V, 5 kV isolation"),
    dict(pn="ATmega328P", cat="Microcontroller", desc="AVR MCU used in Arduino Uno/Nano", pkg="DIP-28 / TQFP-32",
         specs="1.8-5.5 V, 32 KB flash, 2 KB SRAM, 16-20 MHz"),
    dict(pn="ATtiny85", cat="Microcontroller", desc="Small AVR MCU", pkg="DIP-8 / SOIC-8",
         specs="2.7-5.5 V, 8 KB flash, 512 B SRAM, 5 usable I/O"),
    dict(pn="ESP32-WROOM-32", cat="Microcontroller", desc="Wi-Fi + Bluetooth dual-core module", pkg="Module",
         specs="3.0-3.6 V, 240 MHz dual core, 4 MB flash, Wi-Fi TX bursts up to ~500 mA",
         notes="GPIO 34-39 are input-only; GPIO 6-11 are used by flash; ADC2 pins don't work while Wi-Fi is on."),
    dict(pn="ESP-12F", cat="Microcontroller", desc="ESP8266 Wi-Fi module", pkg="Module",
         specs="3.0-3.6 V, 80 MHz, 4 MB flash, TX bursts ~320 mA", notes="Pull GPIO0 low to flash. GPIO15 must be low at boot."),
    dict(pn="CH340G", cat="IC", desc="USB to UART bridge", pkg="SOP-16", specs="3.3 V or 5 V logic",
         notes="Needs a driver on some OSes. CP2102 is the alternative on many ESP boards."),
    dict(pn="CP2102", cat="IC", desc="USB to UART bridge", pkg="QFN-28 / module", specs="3.3 V logic, 3.3 V regulator output ~100 mA"),
    dict(pn="DS3231", cat="IC", desc="Precision RTC", pkg="SOIC-16 / module", specs="I2C 0x68, +/-2 ppm, 2.3-5.5 V, battery backup",
         notes="Many cheap modules charge a CR2032 through a resistor: remove it or use LIR2032."),
    dict(pn="PCF8574", cat="IC", desc="I2C 8-bit GPIO expander", pkg="DIP-16 / SOIC-16",
         specs="I2C 0x20-0x27 (PCF8574A: 0x38-0x3F), 2.5-6 V", notes="Used on LCD I2C backpacks."),
    dict(pn="MAX7219", cat="IC", desc="LED display driver (7-seg / 8x8 matrix)", pkg="DIP-24", specs="4-5.5 V, 3-wire SPI-like, 64 LEDs"),
    # ------------------------------------------------------------------ sensors
    dict(pn="DHT11", cat="Sensor", desc="Temperature and humidity sensor", pkg="module",
         specs="3-5.5 V, 0-50 C +/-2 C, 20-80% RH +/-5%, 1 Hz max"),
    dict(pn="DHT22", cat="Sensor", desc="Temperature and humidity sensor (AM2302)", pkg="module",
         specs="3.3-6 V, -40-80 C +/-0.5 C, 0-100% RH +/-2-5%, 0.5 Hz max"),
    dict(pn="DS18B20", cat="Sensor", desc="1-Wire digital temperature sensor", pkg="TO-92 / waterproof probe",
         specs="3-5.5 V, -55-125 C, +/-0.5 C, 4.7k pull-up on data"),
    dict(pn="HC-SR04", cat="Sensor", desc="Ultrasonic distance sensor", pkg="module",
         specs="5 V, 15 mA, 2-400 cm, 10 us trigger pulse", notes="ECHO is 5 V. Use a divider or level shifter on 3.3 V boards."),
    dict(pn="MPU6050", cat="Sensor", desc="6-axis accelerometer + gyro", pkg="module", specs="I2C 0x68/0x69, 3.3 V chip"),
    dict(pn="BME280", cat="Sensor", desc="Temperature, humidity and pressure sensor", pkg="module",
         specs="I2C 0x76/0x77, 1.8-3.6 V chip",
         notes="Many modules sold as BME280 are really BMP280 (no humidity). Chip ID 0x60=BME280, 0x58=BMP280."),
    dict(pn="BH1750", cat="Sensor", desc="Digital ambient light sensor", pkg="module", specs="I2C 0x23/0x5C, 1-65535 lx"),
    # ------------------------------------------------------------------ modules
    dict(pn="SSD1306", cat="Display", desc="0.96\" 128x64 OLED controller", pkg="module", specs="I2C 0x3C/0x3D (or SPI), 3.3-5 V"),
    dict(pn="SG90", cat="Actuator", desc="Micro servo", pkg="module", specs="4.8-6 V, ~650 mA stall, 1.8 kg.cm",
         notes="Don't power from an Arduino/ESP 5 V pin if several servos move together."),
    dict(pn="28BYJ-48", cat="Actuator", desc="Geared unipolar stepper (5 V)", pkg="module", specs="2048 steps/rev (half-step), driven by ULN2003"),
    dict(pn="NEO-6M", cat="Module", desc="u-blox GPS module", pkg="module", specs="3.3 V chip, ~45 mA tracking, 9600 baud NMEA"),
    dict(pn="nRF24L01+", cat="Module", desc="2.4 GHz radio transceiver", pkg="module",
         specs="1.9-3.6 V (5 V tolerant I/O), 13.5 mA TX, needs clean supply", notes="Add a 10 uF cap across its supply pins."),
]
